from .role import *
from .assassin import *
from .nurse import *
from .prostitute import *
from .scientist import *
from .cook import *
from .teacher import *
from .angel import *
from .gambler import *
from .ghost import *
from .hunter import *
from .cupid import *
from .villager import *